version: "3.0"
services:
  mysql8:
    image: bitnami/postgresql
    container_name: postgresql
    command: |
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on

    ports:
      - "3306:3306"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: root
      POSTGRES_DB: vben_admin
