version: "3.0"

services:
  postgresql:
    image: bitnami/postgresql
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_PASSWORD: 123456
      POSTGRESQL_USERNAME: root
      POSTGRESQL_DATABASE: vben_admin
    volumes:
      - postgresql_data:/bitnami/postgresql
volumes:
  postgresql_data: