spring:
  application:
    name: ${env.appName}
  messages:
    basename: i18n
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://{your mysql ip}:3306/test_em?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: # your username
    password: # your password
logging:
  config: classpath:logback-spring-dev.xml
  file:
    path: classpath:/
    name: log
  charset:
    file: UTF-8
env:
  appName: 'vben admin service'
  version: '0.0.1'
  isEnableSwagger: true
  jwt:
    expire: 30
    tokenHeader: Authorization
    tokenPrefix: 'Bearer'
    privateKey: classpath:private.pem
    publicKey: classpath:public.pem
